version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/FluentFlyoutWPF/"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/FluentFlyout.SourceGenerators/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
