'MainWindow / Media Flyout':
  - changed-files:
      - any-glob-to-any-file: '**/MainWindow.{xaml,cs,xaml.cs}'

'SettingsWindow':
  - changed-files:
      - any-glob-to-any-file: '**/SettingsWindow.{xaml,cs,xaml.cs}'

'Lock Keys Flyout':
  - changed-files:
      - any-glob-to-any-file: '**/LockWindow.{xaml,cs,xaml.cs}'

'Next Up Flyout':
  - changed-files:
      - any-glob-to-any-file: '**/NextUpWindow.{xaml,cs,xaml.cs}'

'Taskbar Widget':
  - changed-files:
      - any-glob-to-any-file: '**/TaskbarWindow.{xaml,cs,xaml.cs}'

# Add translations label to changes within Localization dictionaries except for en-US dictionary
'translations':
  - changed-files:
      - any-glob-to-any-file:
          - '**/Resources/Localization/*'
          - '!**/Resources/Localization/Dictionary-en-US.xaml'
