name: Feature request
description: Suggest an idea for this project
title: "[FEATURE REQUEST] Add Title Here"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        <p align="center">
        	<picture>
        		<source width="50%" alt="fluentflyout-title" media="(prefers-color-scheme: dark)" srcset="https://github.com/user-attachments/assets/daa2969f-8ad2-4832-8253-26133a50c921" />
        		<source width="50%" alt="fluentflyout-title" media="(prefers-color-scheme: light)" srcset="https://github.com/user-attachments/assets/3e75e514-b9a6-40e3-b170-af9d29a82bb4" />
        		<img width="50%" alt="fluentflyout-title" src="https://github.com/user-attachments/assets/daa2969f-8ad2-4832-8253-26133a50c921">
        	</picture>
        </p>

        # FluentFlyout Feature Request Form

        Before continuing, confirm that you have done the following:

        * I have searched that there is no [existing feature report](https://github.com/unchihugo/FluentFlyout/issues?q=is%3Aissue%20state%3Aopen%20label%3Aenhancement) regarding my feature request
        * I have read the [FAQ page](https://fluentflyout.com/faq/) and there is no answer to my feature request

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "A clear and concise description of what you'd like to have."
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: "Add any other context or screenshots about the feature request here."
  - type: checkboxes
    id: checklist
    attributes:
      label: "Confirm that you have done the following:"
      options:
        - label: "I have searched that there is no existing issue regarding my feature request"
          required: true
        - label: "I have read the [FAQ](https://fluentflyout.com/faq/) and there is no answer to my feature request"
          required: true
